export const UPDATE_ONBOARDING_STATUS = "UPDATE_ONBOARDING_STATUS";
export const UPDATE_USER_LOGIN = "UPDATE_USER_LOGIN";
export const UPDATE_USER_ACCESS_TOKEN = "UPDATE_USER_ACCESS_TOKEN";
export const UPDATE_APP_MODE_TYPE = "UPDATE_APP_MODE_TYPE";
